Testing
YunoHost-Apps/framagames_ynh pull request #11
Opened 2021-04-24 09:34 UTC by ericgaspar

- Fix linter warnings

2021-04-24 09:34 UTC, ericgaspar commented
!testme

2021-04-25 18:21 UTC, yalh76 requested changes

2021-04-25 18:21 UTC, yalh76 commented on check_process
> -		upgrade=1	from_commit=bd2c87a6fd4212771f9c06e7965598a5ea744ffc
you should keep a test upgrade from previous version

2021-04-25 18:21 UTC, yalh76 commented on scripts/install
>  chmod -R 775 $final_path
You should remove `-R` to `chmod`

2021-04-25 18:21 UTC, yalh76 commented on scripts/install
> +ynh_script_progression --message="Installation of $app completed" --last
```suggestion
ynh_script_progression --message="Installation of $app completed"
```

2021-04-25 18:21 UTC, yalh76 commented on scripts/remove
> +ynh_script_progression --message="Removal of $app completed" --last
```suggestion
ynh_script_progression --message="Removal of $app completed"
```

2021-04-25 18:21 UTC, yalh76 commented on scripts/restore
> +ynh_script_progression --message="Recreating the dedicated system user..." --weight=1
```suggestion
ynh_script_progression --message="Recreating the dedicated system user..."
```

2021-04-25 18:21 UTC, yalh76 commented on scripts/restore
> +ynh_system_user_create --username=$app --home_dir="$final_path"
```suggestion
ynh_system_user_create --username=$app
```

2021-04-25 18:21 UTC, yalh76 commented on scripts/restore
> +chmod -R 775 $final_path
```suggestion
chmod 775 $final_path
```

2021-04-25 18:21 UTC, yalh76 commented on scripts/restore
> +ynh_script_progression --message="Restoration completed for $app" --last
```suggestion
ynh_script_progression --message="Restoration completed for $app"
```

2021-04-25 18:21 UTC, yalh76 commented on scripts/upgrade
>  chmod -R 775 $final_path
```suggestion
chmod 775 $final_path
```

2021-04-25 18:21 UTC, yalh76 commented on scripts/upgrade
> +ynh_script_progression --message="Upgrade of $app completed" --last
```suggestion
ynh_script_progression --message="Upgrade of $app completed"
```

2021-04-25 21:02 UTC, yalh76 approved these changes

2021-04-25 21:03 UTC, yalh76 commented
!testme

2021-04-26 05:37 UTC, merged